backend:
  name: git-gateway
  branch: main # Agar aapki GitHub branch ka naam 'master' hai to yahan master likhein

media_folder: "images/uploads" # Jo images client upload karega wo is folder mein jayengi
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products" # Har nai product ki detail is folder mein save hogi
    create: true # Taake client nai product add kar sake
    slug: "{{slug}}"
    fields:
      - {label: "Product Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "number", value_type: "float"}
      - {label: "Product Image", name: "image", widget: "image"}
      - {label: "Description", name: "body", widget: "text"}

